### ISSUE TITLE
Install xmipp alone get some err

### ISSUE THREAD

**Issue by shuaishuairuirui** [scipion-em/scipion-pyworkflow#260] opened 2021-06-06 05:39 UTC
lib/libXmipp.so: undefined reference to non-virtual thunk to H5::H5File::throwException(std::string const&, std::string const&) const' lib/libXmipp.so: undefined reference to H5::H5File::throwException(std::string const&, std::string const&) const'
/home/spider/xmipp-bundle/src/xmippCore/lib/libXmippCore.so: undefined reference to `H5::H5Location::getFileName() const'
collect2: error: ld returned 1 exit status
scons: *** [bin/xmipp_angular_accuracy_pca] Error 1
scons: building terminated because of errors.

Some error occurred during the compilation of 'xmipp' ('bin/xmipp_angular_accuracy_pca').

Checking CUDA configuration ...
/usr/local/cuda-10.2/bin/nvcc -c -w --x cu -D_FORCE_INLINES -Xcompiler -fPIC -ccbin gcc-c++ -std=c++11 --expt-extended-lambda -gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_50,code=compute_50 -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_61,code=compute_61 -I../ -I/home/spider/anaconda3/include xmipp_cuda_test.cpp -o xmipp_cuda_test.o
gcc-c++: No such file or directory
Check the NVCC, NVCC_CXXFLAGS and INCDIRFLAGS
Cannot compile with NVCC, continuing without CUDA

Can you give me some helps?Thanks very much.

**Comment by DStrelak** [comment] 2021-06-07 09:12
Closing. Duplicate of https://github.com/I2PC/xmipp/issues/391
@shuaishuairuirui please don't create duplicate tickets.

**Closed by DStrelak** 2021-06-07 09:12 UTC
