### ISSUE TITLE
'Volume' object has no attribute 'getCompatibility' in test of scipion v3.6.1

### ISSUE THREAD

**Issue by HamishGBrown** [scipion-em/scipion-pyworkflow#563] opened 2024-10-02 23:25 UTC
Hi Scipion developers,

I just installed Scipion v3.6.1 (install seemed unproblematic) and encountered the following errors during the test. The workstation is running Linux Mint v20.1 and Nvidia driver version 525.147.05. Please let me know what else I might need to provide for you to investigate.

```
$ scipion3 tests pwem.tests.protocols.test_protocols_import_volumes

Logging configured. STDOUT --> /home/bio21em1/ScipionUserData/projects/TestImportVolumes/Runs/000537_ProtUnionSet/logs/run.stdout , STDERR --> /home/bio21em1/ScipionUserData/projects/TestImportVolumes/Runs/000537_ProtUnionSet/logs/run.stderr
RESUMING PROTOCOL -----------------
Protocol starts
Hostname: Freyja
PID: 2005965
pyworkflow: 3.9.0
plugin: pwem - https://github.com/scipion-em/scipion-em
plugin v: 3.9.1(production)
plugin binary v: 
currentDir: /home/bio21em1/ScipionUserData/projects/TestImportVolumes
workingDir: Runs/000537_ProtUnionSet
runMode: Continue
          MPI: 1
      threads: 1
Protocol has validation errors:
Protocol validation failed. It usually happens because there are some input missing. Please check if the error message gives you any hint:
Error: AttributeError 
Description: 'Volume' object has no attribute 'getCompatibilityDict' 
Traceback:
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 2105, in validate
    childErrors = self._validate()

  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_sets.py", line 330, in _validate
    return self._checkSetsCompatibility()

  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_sets.py", line 335, in _checkSetsCompatibility
    attrs = self.inputSets[0].get().getCompatibilityDict()
```

and during the final test:

```
$ scipion3 tests xmipp3.tests.test_protocols_xmipp_3d.TestXmippProjMatching

Traceback (most recent call last):
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 207, in run
    self._run()
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1509, in _run
    self._insertAllSteps()  # Define steps for execute later
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_projmatch/protocol_projmatch.py", line 99, in _insertAllSteps
    self._insertItersSteps()
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_projmatch/protocol_projmatch.py", line 122, in _insertItersSteps
    insertAngularClassAverageStep(self, iterN, refN)
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_projmatch/projmatch_steps.py", line 501, in insertAngularClassAverageStep
    self._insertRunJobStep('xmipp_angular_class_average', args % params, processorsToUse, **kwargs)
AttributeError: 'XmippProtProjMatch' object has no attribute '_insertRunJobStep'

*************** end of STD ERR *********************

[   FAILED ] TestXmippProjMatching.testXmippProjMatching


Traceback (most recent call last):
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/tests/test_protocols_xmipp_3d.py", line 1123, in testXmippProjMatching
    self.launchProtocol(protProjMatch)
  File "/home/bio21em1/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/tests/tests.py", line 120, in launchProtocol
    raise Exception("Protocol %s execution failed. See last log lines above for more details." % prot.getRunName())
Exception: Protocol xmipp3 - projection matching execution failed. See last log lines above for more details.
```

**Comment by pconesa** [comment] 2024-10-04 10:14
Thanks and sorry. First issue will be fixed in the nest release of scipion-em (3.9.2). Hopefully will be released today. The problem only affects when joining volumes which is rare but the test you are running test this case.

The second.... (projectionMatching)... unless you are really interested in this method.... we can fix this. Maybe use other test.. this method may be deprecated soon and the test too.

**Comment by azazellochg** [comment] 2024-10-04 11:04
@pconesa the xmipp test comes from the docs that check if the installation was successful. The idea is to test xmipp+cuda+openmpi which are all used in this test. I'm happy if someone provides an alternative test(s).

**Comment by azazellochg** [comment] 2024-10-04 11:19
The issue is now fixed in https://github.com/scipion-em/scipion-em/pull/538

**Comment by pconesa** [comment] 2024-10-04 12:55
Yes, first issue fix was released. We'll find a better test for that combination. Actually, I think projection matching does not use cuda?

**Comment by azazellochg** [comment] 2024-10-04 13:19
yes, it uses GPU: https://github.com/I2PC/scipion-em-xmipp/blob/devel/xmipp3/protocols/protocol_projmatch/projmatch_form.py#L41

**Comment by pconesa** [comment] 2024-10-05 18:08
Both fixes are released now. 

scipion3 update

Should bring them

**Closed by pconesa** 2024-10-05 18:08 UTC
